export const GU_TERM_MAPS = {
  planets: {
    Sun: "સૂર્ય", Moon: "ચંદ્ર", Mars: "મંગળ", Mercury: "બુધ", Jupiter: "ગુરુ", Venus: "શુક્ર", Saturn: "શનિ", Rahu: "રાહુ", Ketu: "કેતુ",
  },
  signs: {
    Aries: "મેષ", Taurus: "વૃષભ", Gemini: "મિથુન", Cancer: "કર્ક", Leo: "સિંહ", Virgo: "કન્યા", Libra: "તુલા", Scorpio: "વૃશ્ચિક", Sagittarius: "ધનુ", Capricorn: "મકર", Aquarius: "કુંભ", Pisces: "મીન",
  },
  weekdays: {
    Sunday: "રવિવાર", Monday: "સોમવાર", Tuesday: "મંગળવાર", Wednesday: "બુધવાર", Thursday: "ગુરુવાર", Friday: "શુક્રવાર", Saturday: "શનિવાર",
  },
  houses: {
    "1": "પ્રથમ ભાવ", "2": "દ્વિતીય ભાવ", "3": "તૃતીય ભાવ", "4": "ચતુર્થ ભાવ", "5": "પંચમ ભાવ", "6": "ષષ્ઠ ભાવ", "7": "સપ્તમ ભાવ", "8": "અષ્ટમ ભાવ", "9": "નવમ ભાવ", "10": "દશમ ભાવ", "11": "એકાદશ ભાવ", "12": "દ્વાદશ ભાવ",
  },
  nakshatras: {
    Ashwini: "અશ્વિની",
    Bharani: "ભરણી",
    Krittika: "કૃત્તિકા",
    Rohini: "રોહિણી",
    Mrigashira: "મૃગશીર્ષ",
    Ardra: "આર્દ્રા",
    Punarvasu: "પુનર્વસુ",
    Pushya: "પુષ્ય",
    Ashlesha: "આશ્લેષા",
    Magha: "મધા",
    "Purva Phalguni": "પૂર્વ ફાલ્ગુની",
    "Uttara Phalguni": "ઉત્તર ફાલ્ગુની",
    Hasta: "હસ્ત",
    Chitra: "ચિત્રા",
    Swati: "સ્વાતી",
    Vishakha: "વિશાખા",
    Anuradha: "અનુરાધા",
    Jyeshtha: "જ્યેષ્ઠા",
    Mula: "મૂલ",
    "Purva Ashadha": "પૂર્વાષાઢ",
    "Uttara Ashadha": "ઉત્તરાષાઢ",
    Shravana: "શ્રવણ",
    Dhanishta: "ધનિષ્ઠા",
    Shatabhisha: "શતભિષા",
    "Purva Bhadrapada": "પૂર્વ ભાદ્રપદ",
    "Uttara Bhadrapada": "ઉત્તર ભાદ્રપદ",
    Revati: "રેવતી",
  },
  months: {
    January: "જાન્યુઆરી",
    February: "ફેબ્રુઆરી",
    March: "માર્ચ",
    April: "એપ્રિલ",
    May: "મે",
    June: "જુન",
    July: "જુલાઈ",
    August: "ઑગસ્ટ",
    September: "સપ્ટેમ્બર",
    October: "ઑક્ટોબર",
    November: "નવેમ્બર",
    December: "ડિસેમ્બર",
  },
  misc: {
    "Ascendant": "લગ્ન",
    "Moon Sign": "ચંદ્ર રાશિ",
    "Sun Sign": "સૂર્ય રાશિ",
  },
};
