export const TE_TERM_MAPS = {
  planets: {
    Sun: "సూర్యుడు", Moon: "చంద్రుడు", Mars: "కుజుడు", Mercury: "బుధుడు", Jupiter: "గురువు", Venus: "శుక్రుడు", Saturn: "శని", Rahu: "రాహు", Ketu: "కేతు",
  },
  signs: {
    Aries: "మేషం", Taurus: "వృషభం", Gemini: "మిథునం", Cancer: "కర్కాటకం", Leo: "సింహం", Virgo: "కన్య", Libra: "తులా", Scorpio: "వృశ్చికం", Sagittarius: "ధనుస్సు", Capricorn: "మకరం", Aquarius: "కుంభం", Pisces: "మీనం",
  },
  weekdays: {
    Sunday: "ఆదివారం", Monday: "సోమవారం", Tuesday: "మంగళవారం", Wednesday: "బుధవారం", Thursday: "గురువారం", Friday: "శుక్రవారం", Saturday: "శనివారం",
  },
  houses: {
    "1": "ప్రథమ భావం", "2": "ద్వితీయ భావం", "3": "తృతీయ భావం", "4": "చతుర్థ భావం", "5": "పంచమ భావం", "6": "షష్ఠ భావం", "7": "సప్తమ భావం", "8": "అష్టమ భావం", "9": "నవమ భావం", "10": "దశమ భావం", "11": "ఏకాదశ భావం", "12": "ద్వాదశ భావం",
  },
  nakshatras: {
    Ashwini: "అశ్విని",
    Bharani: "భరణి",
    Krittika: "కృత్తిక",
    Rohini: "రోహిణి",
    Mrigashira: "మృగశిర",
    Ardra: "ఆర్ద్ర",
    Punarvasu: "పునర్వసు",
    Pushya: "పుష్యమి",
    Ashlesha: "ఆశ్లేష",
    Magha: "మఘ",
    "Purva Phalguni": "పూర్వ ఫల్గుణి",
    "Uttara Phalguni": "ఉత్తర ఫల్గుణి",
    Hasta: "హస్త",
    Chitra: "చిత్ర",
    Swati: "స్వాతి",
    Vishakha: "విశాఖ",
    Anuradha: "అనూరాధ",
    Jyeshtha: "జ్యేష్ఠ",
    Mula: "మూల",
    "Purva Ashadha": "పూర్వాషాఢ",
    "Uttara Ashadha": "ఉత్తరాషాఢ",
    Shravana: "శ్రవణం",
    Dhanishta: "ధనిష్ఠ",
    Shatabhisha: "శతభిషం",
    "Purva Bhadrapada": "పూర్వ భాద్రపద",
    "Uttara Bhadrapada": "ఉత్తర భాద్రపద",
    Revati: "రేవతి",
  },
  months: {
    January: "జనవరి",
    February: "ఫిబ్రవరి",
    March: "మార్చి",
    April: "ఏప్రిల్",
    May: "మే",
    June: "జూన్",
    July: "జూలై",
    August: "ఆగస్టు",
    September: "సెప్టెంబర్",
    October: "అక్టోబర్",
    November: "నవంబర్",
    December: "డిసెంబర్",
  },
  misc: {
    Mahadasha: "మహాదశ",
    Antardasha: "అంతర్దశ",
    "Sade Sati": "ఏడున్నర శని",
    "Not Active": "ప్రస్తుతం లేదు",
    "Rising Phase": "ప్రారంభ దశ",
    "Peak Phase": "శిఖర దశ",
    "Setting Phase": "చివరి దశ",
    Ascendant: "లగ్నం",
    "Moon Sign": "చంద్ర రాశి",
    "Birth Nakshatra": "జన్మ నక్షత్రం",
    "Planetary Positions": "గ్రహ స్థితులు",
    "House Analysis": "భావ విశ్లేషణ",
    "Career Analysis": "కెరీర్ విశ్లేషణ",
    "Marriage Analysis": "వివాహ విశ్లేషణ",
    "Health Guidance": "ఆరోగ్య మార్గదర్శనం",
    house: "భావం",
    houses: "భావాలు",
    sign: "రాశి",
    signs: "రాశులు",
    marriage: "వివాహం",
    career: "వృత్తి",
    health: "ఆరోగ్యం",
    guidance: "మార్గదర్శనం",
    analysis: "విశ్లేషణ",
    phase: "దశ",
    active: "చురుకుగా",
    current: "ప్రస్తుత",
    period: "కాలం",
    prediction: "అంచనా",
    remedy: "పరిహారం",
    present: "ఉంది",
    absent: "లేదు",
    nullified: "నిరాకరించబడింది",
    partial: "ఆంశికం",
    high: "అధిక",
    medium: "మధ్యస్థ",
    low: "తక్కువ",
    none: "లేదు",
    strong: "బలమైన",
    weak: "బలహీన",
    moderate: "మధ్యస్థ",
    male: "పురుషుడు",
    female: "మహిళ",
    spouse: "జీవిత భాగస్వామి",
    partner: "భాగస్వామి",
    years: "సంవత్సరాలు",
    year: "సంవత్సరం",
    months: "నెలలు",
    month: "నెల",
    Siddha: "సిద్ధ",
    Mangala: "మంగళ",
    Pingala: "పింగళ",
    Dhanya: "ధన్య",
    Bhramari: "భ్రమరి",
    Bhadrika: "భద్రికా",
    Ulka: "ఉల్కా",
    Sankata: "సంకటా",
    Debilitated: "నిచ్చ",
    Exaltation: "ఉచ్చ",
    Retrograde: "వక్ర",
  },
};
