export const HI_TERM_MAPS = {
  planets: {
    Sun: "सूर्य", Moon: "चंद्र", Mars: "मंगल", Mercury: "बुध", Jupiter: "गुरु", Venus: "शुक्र", Saturn: "शनि", Rahu: "राहु", Ketu: "केतु",
  },
  signs: {
    Aries: "मेष", Taurus: "वृषभ", Gemini: "मिथुन", Cancer: "कर्क", Leo: "सिंह", Virgo: "कन्या", Libra: "तुला", Scorpio: "वृश्चिक", Sagittarius: "धनु", Capricorn: "मकर", Aquarius: "कुंभ", Pisces: "मीन",
  },
  weekdays: {
    Sunday: "रविवार", Monday: "सोमवार", Tuesday: "मंगलवार", Wednesday: "बुधवार", Thursday: "गुरुवार", Friday: "शुक्रवार", Saturday: "शनिवार",
  },
  houses: {
    "1": "प्रथम भाव", "2": "द्वितीय भाव", "3": "तृतीय भाव", "4": "चतुर्थ भाव", "5": "पंचम भाव", "6": "षष्ठ भाव", "7": "सप्तम भाव", "8": "अष्टम भाव", "9": "नवम भाव", "10": "दशम भाव", "11": "एकादश भाव", "12": "द्वादश भाव",
  },
  nakshatras: {
    Ashwini: "अश्विनी",
    Bharani: "भरणी",
    Krittika: "कृत्तिका",
    Rohini: "रोहिणी",
    Mrigashira: "मृगशीर्ष",
    Ardra: "आर्द्रा",
    Punarvasu: "पुनर्वसु",
    Pushya: "पुष्य",
    Ashlesha: "आश्लेषा",
    Magha: "मघा",
    "Purva Phalguni": "पूर्व फाल्गुनी",
    "Uttara Phalguni": "उत्तर फाल्गुनी",
    Hasta: "हस्त",
    Chitra: "चित्रा",
    Swati: "स्वाती",
    Vishakha: "विशाखा",
    Anuradha: "अनुराधा",
    Jyeshtha: "ज्येष्ठा",
    Mula: "मूल",
    "Purva Ashadha": "पूर्वाषाढ़ा",
    "Uttara Ashadha": "उत्तराषाढ़ा",
    Shravana: "श्रवण",
    Dhanishta: "धनिष्ठा",
    Shatabhisha: "शतभिषा",
    "Purva Bhadrapada": "पूर्व भाद्रपद",
    "Uttara Bhadrapada": "उत्तर भाद्रपद",
    Revati: "रेवती",
  },
  months: {
    January: "जनवरी",
    February: "फरवरी",
    March: "मार्च",
    April: "अप्रैल",
    May: "मई",
    June: "जून",
    July: "जुलाई",
    August: "अगस्त",
    September: "सितंबर",
    October: "अक्टूबर",
    November: "नवंबर",
    December: "दिसंबर",
  },
  misc: {
    Mahadasha: "महादशा",
    Antardasha: "अंतरदशा",
    "Sade Sati": "साढ़ेसाती",
    "Not Active": "सक्रिय नहीं",
    "Rising Phase": "प्रारंभिक चरण",
    "Peak Phase": "चरम चरण",
    "Setting Phase": "अंतिम चरण",
    Ascendant: "लग्न",
    "Moon Sign": "चंद्र राशि",
    "Birth Nakshatra": "जन्म नक्षत्र",
    "Planetary Positions": "ग्रह स्थितियां",
    "House Analysis": "भाव विश्लेषण",
    "Career Analysis": "कैरियर विश्लेषण",
    "Marriage Analysis": "विवाह विश्लेषण",
    "Health Guidance": "स्वास्थ्य मार्गदर्शन",
    house: "भाव",
    houses: "भाव",
    sign: "राशि",
    signs: "राशियां",
    marriage: "विवाह",
    career: "कैरियर",
    health: "स्वास्थ्य",
    guidance: "मार्गदर्शन",
    analysis: "विश्लेषण",
    phase: "चरण",
    active: "सक्रिय",
    current: "वर्तमान",
    period: "अवधि",
    prediction: "भविष्यवाणी",
    remedy: "उपाय",
    present: "उपस्थित",
    absent: "अनुपस्थित",
    nullified: "निरस्त",
    partial: "आंशिक",
    high: "उच्च",
    medium: "मध्यम",
    low: "कम",
    none: "नहीं",
    strong: "मजबूत",
    weak: "कमज़ोर",
    moderate: "मध्यम",
    male: "पुरुष",
    female: "महिला",
    spouse: "जीवनसाथी",
    partner: "साथी",
    years: "वर्ष",
    year: "वर्ष",
    months: "महीने",
    month: "माह",
    Siddha: "सिद्ध",
    Mangala: "मंगला",
    Pingala: "पिंगला",
    Dhanya: "धन्या",
    Bhramari: "भ्रमरी",
    Bhadrika: "भद्रिका",
    Ulka: "उल्का",
    Sankata: "संकटा",
    Debilitated: "नीच",
    Exaltation: "उच्च",
    Retrograde: "वक्री",
  },
};
