/**
 * finalize-kundli-report — Stage 3 of the Kundli pipeline.
 *
 * Runs QA validation, localization, language QC, chart fetching, and saves
 * the completed report. Triggered by translate-kundli-report after the
 * translation sweep is done.
 *
 * Flow:  process-kundli-job → translate-kundli-report → [this]
 */

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.80.0";

import { runQAValidation, sanitizeReportContent } from "../_shared/generate-kundli-report/qa-agent.ts";
import { setAgentLanguageContext } from "../_shared/generate-kundli-report/agent-base.ts";
import { getLanguagePack, normalizeLanguage } from "../_shared/language-packs/index.ts";
import { runLanguageQc } from "../_shared/language-qc.ts";
import type { SupportedLanguage } from "../_shared/language-packs/types.ts";
import { createJobEvent, touchJobHeartbeat } from "../_shared/job-events.ts";
import { localizeStructuredReportTerms } from "../_shared/language-localize.ts";
import { upsertKundliGeneratedReport } from "../_shared/kundli-audit.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function isLanguagePipelineV2Enabled(language: SupportedLanguage): boolean {
  if (language === "hi" || language === "te") return true;
  if (language === "en") return false;
  return false;
}

function parseBirthTime(rawTime: string): { hour: number; min: number } {
  const input = String(rawTime || "").trim();
  if (!input) throw new Error("Invalid birth time: empty");
  const ampm = input.match(/\b(am|pm)\b/i)?.[1]?.toLowerCase();
  const cleaned = input.replace(/\s*(am|pm)\s*/i, "");
  const parts = cleaned.split(":").map((x) => Number(x));
  let hour = parts[0];
  const min = parts.length > 1 ? parts[1] : 0;
  if (!Number.isFinite(hour) || !Number.isFinite(min)) {
    throw new Error(`Invalid birth time format: "${rawTime}"`);
  }
  if (ampm) {
    hour = hour % 12;
    if (ampm === "pm") hour += 12;
  }
  return { hour, min };
}

function stripAiDisclosure<T>(value: T): T {
  const cleanText = (text: string): string =>
    text
      .replace(/\bAI[- ]generated\b/gi, "generated")
      .replace(/\bgenerated by AI\b/gi, "generated")
      .replace(/\bAI[- ]powered\b/gi, "")
      .replace(/\bartificial intelligence\b/gi, "")
      .replace(/[ \t]{2,}/g, " ")
      .trim();

  if (typeof value === "string") return cleanText(value) as T;
  if (Array.isArray(value)) return value.map((item) => stripAiDisclosure(item)) as T;
  if (value && typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(obj)) out[key] = stripAiDisclosure(val);
    return out as T;
  }
  return value;
}

// ── English report gibberish cleanup ─────────────────────────────────────────

/**
 * Detect whether a string is mostly gibberish.
 * Returns true if the text has hallmarks of AI-garbled output.
 */
function isGibberishText(text: string): boolean {
  if (!text || text.length < 10) return false;

  // 1. Excessive consecutive consonants (no language has 6+ consonants in a row)
  if (/[bcdfghjklmnpqrstvwxyz]{6,}/i.test(text)) return true;

  // 2. Same character repeated 4+ times
  if (/(.)\1{3,}/.test(text)) return true;

  // 3. Mostly non-ASCII non-Devanagari control/garbage characters
  const controlChars = text.replace(/[\x20-\x7E\u0900-\u097F\u0C00-\u0C7F\n\r\t]/g, "");
  if (controlChars.length > text.length * 0.3) return true;

  return false;
}

/**
 * Clean a single English text string:
 *  - Strip Devanagari / Telugu script (shouldn't appear in English fields)
 *  - Remove garbled character sequences
 *  - Collapse excess whitespace
 *  - Remove incomplete trailing sentences
 */
function cleanEnglishText(text: string, allowDevanagari = false): string {
  if (!text || typeof text !== "string") return text;

  let cleaned = text;

  // Remove Devanagari (U+0900–U+097F) and Telugu (U+0C00–U+0C7F) from non-mantra fields
  if (!allowDevanagari) {
    cleaned = cleaned.replace(/[\u0900-\u097F\u0C00-\u0C7F]+/g, "").trim();
  }

  // Remove zero-width chars, soft hyphens, and other invisible Unicode
  cleaned = cleaned.replace(/[\u200B-\u200F\u2028-\u202F\u00AD\uFEFF]/g, "");

  // Remove sequences of random symbols (3+ non-word non-space chars in a row)
  cleaned = cleaned.replace(/[^\w\s'".,;:!?()\-\/]{3,}/g, "");

  // Remove same character repeated 4+ times
  cleaned = cleaned.replace(/(.)\1{3,}/g, "$1$1");

  // Collapse multiple spaces / newlines
  cleaned = cleaned.replace(/[ \t]{2,}/g, " ").replace(/\n{3,}/g, "\n\n").trim();

  // Remove incomplete sentence fragments at the end (ending mid-word or with trailing comma)
  cleaned = cleaned.replace(/,\s*$/, ".").replace(/\s+\w{1,3}$/, ".");

  return cleaned;
}

/** Keys whose string values may legitimately contain Devanagari (mantras) */
const MANTRA_KEYS = new Set([
  "mantra", "mantras", "pronunciation", "chant",
  "termSanskrit", "scripturalSource", "scripturalReference",
  "scripturalBasis", "consecrationMethod",
]);

/**
 * Recursively clean all text fields in the English report.
 * Preserves Devanagari in mantra-related fields.
 */
function cleanEnglishReport<T>(value: T, parentKey = ""): T {
  if (typeof value === "string") {
    const allowDev = MANTRA_KEYS.has(parentKey);
    // If the entire string is gibberish, replace with empty string
    if (isGibberishText(value) && !allowDev) {
      const cleaned = cleanEnglishText(value, false);
      // If after cleaning it's basically empty, return a placeholder
      if (cleaned.length < 5) return "" as unknown as T;
      return cleaned as unknown as T;
    }
    return cleanEnglishText(value, allowDev) as unknown as T;
  }
  if (Array.isArray(value)) {
    return value
      .map((item) => cleanEnglishReport(item, parentKey))
      .filter((item) => {
        // Remove array entries that are empty strings after cleanup
        if (typeof item === "string" && item.trim() === "") return false;
        return true;
      }) as unknown as T;
  }
  if (value && typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(obj)) {
      out[key] = cleanEnglishReport(val, key);
    }
    return out as T;
  }
  return value;
}

// ── Chart SVG fetching ──────────────────────────────────────────────────────

function localizeChartSvgText(svg: string, language: string): string {
  if (language === "hi" || language === "te") return svg;
  const replacements: [string, string][] = [
    ["\u0936\u0941", "VE"], ["\u092C\u0941", "ME"], ["\u092E\u0902", "MA"],
    ["\u091A\u0902", "MO"], ["\u0938\u0942", "SU"], ["\u0917\u0941", "JU"],
    ["\u0930\u093E", "RA"], ["\u0915\u0947", "KE"], ["\u0936", "SA"],
  ];
  let result = svg;
  for (const [hindi, eng] of replacements) {
    result = result.replaceAll(hindi, eng);
  }
  return result;
}

const PDF_CHART_TYPES = ["D1","D2","D3","D4","D7","D9","D10","D12","D20","D24","D27","D60"] as const;

const CHART_INFO: Record<string, { name: string; nameHindi: string; purpose: string }> = {
  D1:  { name: "Rashi (Birth Chart)",       nameHindi: "\u0930\u093E\u0936\u093F \u091A\u0915\u094D\u0930",         purpose: "Overall life assessment" },
  D2:  { name: "Hora",                      nameHindi: "\u0939\u094B\u0930\u093E",               purpose: "Wealth and finances" },
  D3:  { name: "Drekkana",                  nameHindi: "\u0926\u094D\u0930\u0947\u0915\u094D\u0915\u093E\u0923",          purpose: "Siblings and courage" },
  D4:  { name: "Chaturthamsa",              nameHindi: "\u091A\u0924\u0941\u0930\u094D\u0925\u093E\u0902\u0936",          purpose: "Fortune and property" },
  D7:  { name: "Saptamsa",                  nameHindi: "\u0938\u092A\u094D\u0924\u093E\u0902\u0936",            purpose: "Children and progeny" },
  D9:  { name: "Navamsa",                   nameHindi: "\u0928\u0935\u093E\u0902\u0936",              purpose: "Marriage and spouse" },
  D10: { name: "Dasamsa",                   nameHindi: "\u0926\u0936\u093E\u0902\u0936",              purpose: "Career and profession" },
  D12: { name: "Dwadasamsa",                nameHindi: "\u0926\u094D\u0935\u093E\u0926\u0936\u093E\u0902\u0936",          purpose: "Parents and ancestry" },
  D20: { name: "Vimsamsa",                  nameHindi: "\u0935\u093F\u0902\u0936\u093E\u0902\u0936",            purpose: "Spiritual progress" },
  D24: { name: "Chaturvimsamsa",            nameHindi: "\u091A\u0924\u0941\u0930\u094D\u0935\u093F\u0902\u0936\u093E\u0902\u0936",       purpose: "Education and learning" },
  D27: { name: "Bhamsa",                    nameHindi: "\u092D\u093E\u0902\u0936",               purpose: "Strength and weakness" },
  D60: { name: "Shashtiamsa",               nameHindi: "\u0937\u0937\u094D\u091F\u094D\u092F\u0902\u0936",           purpose: "Past life karma" },
};

async function fetchOneChartSvg(
  chartType: string,
  payload: Record<string, unknown>,
): Promise<string | null> {
  try {
    const res = await fetch(
      `https://api-sbox.a4b.io/gw2/seer/external/v1/chart/horo-image/${chartType}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json", "x-fe-server": "true", "x-afb-r-uid": "7160881" },
        body: JSON.stringify(payload),
      }
    );
    if (!res.ok) { console.warn(`\u26A0\uFE0F [CHARTS] ${chartType} HTTP ${res.status}`); return null; }
    const data = await res.json();
    return (data?.data?.svg as string) || null;
  } catch (err) {
    console.warn(`\u26A0\uFE0F [CHARTS] ${chartType} fetch error:`, err);
    return null;
  }
}

async function fetchKundaliCharts(
  day: number, month: number, year: number,
  hour: number, minute: number,
  lat: number, lon: number, tzone: number,
  language: string = "en",
): Promise<Array<{ type: string; name: string; nameHindi: string; purpose: string; svg: string }>> {
  const payload = { day, month, year, hour, minute, lat, lon, tzone, chartType: "North", image_type: "svg", language };
  const results = await Promise.allSettled(
    PDF_CHART_TYPES.map(async (ct) => {
      const rawSvg = await fetchOneChartSvg(ct, payload);
      if (!rawSvg) throw new Error("no svg");
      const svg = localizeChartSvgText(rawSvg, language);
      return { type: ct, svg, ...CHART_INFO[ct] };
    })
  );
  const charts = results
    .filter((r): r is PromiseFulfilledResult<any> => r.status === "fulfilled")
    .map((r) => r.value);
  console.log(`\uD83D\uDCCA [CHARTS] Fetched ${charts.length}/${PDF_CHART_TYPES.length} chart SVGs`);
  return charts;
}

// ── QA with timeout ─────────────────────────────────────────────────────────

async function runQaWithTimeout(report: Record<string, any>, timeoutMs = 45000): Promise<any> {
  const timeoutFallback = {
    issues: [{
      section: "qa", severity: "warning", issueType: "timeout",
      description: `QA validation exceeded ${timeoutMs}ms and returned fallback validation.`,
      suggestedFix: "Review this report manually if strict QA verification is required.",
    }],
    blockedContent: [],
    overallScore: 7,
    approved: true,
  };
  try {
    const result = await Promise.race([
      runQAValidation(report),
      new Promise<any>((resolve) => setTimeout(() => resolve(timeoutFallback), timeoutMs)),
    ]);
    return result || timeoutFallback;
  } catch {
    return timeoutFallback;
  }
}

// ── Main handler ────────────────────────────────────────────────────────────

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const supabaseAdmin = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
  );

  let jobId: string | undefined;

  try {
    const body = await req.json();
    jobId = body.jobId;
    console.log(`\uD83C\uDFC1 [FINALIZE-JOB] Starting finalization for job: ${jobId}`);

    // Load job record with translated report
    const { data: job, error: fetchError } = await supabaseAdmin
      .from("kundli_report_jobs")
      .select("*")
      .eq("id", jobId)
      .single();

    if (fetchError || !job) {
      console.error("\u274C [FINALIZE-JOB] Job not found:", jobId);
      return new Response(JSON.stringify({ error: "Job not found" }), { status: 404 });
    }

    let report = job.report_data as Record<string, any>;
    if (!report) throw new Error("No report_data found — earlier stages may not have completed");

    const requestedLanguage = normalizeLanguage(job.language || "en");
    const useLanguagePipelineV2 = isLanguagePipelineV2Enabled(requestedLanguage);
    const effectiveGenLang: SupportedLanguage = useLanguagePipelineV2 ? requestedLanguage : "en";
    const activeLanguagePack = getLanguagePack(requestedLanguage);
    setAgentLanguageContext(effectiveGenLang);

    let totalTokens = report.tokensUsed || 0;
    const [year, month, day] = String(job.date_of_birth).split("-").map(Number);
    const { hour, min } = parseBirthTime(String(job.time_of_birth));

    // ── QA Validation ──────────────────────────────────────────────────────
    await updateJobStatus(supabaseAdmin, jobId!, "processing", "Running quality checks", 92, "progress");
    const qaResult = await runQaWithTimeout(report);
    if (qaResult.blockedContent.length > 0 || qaResult.issues.some((i: any) => i.severity === "critical")) {
      report = sanitizeReportContent(report);
    }
    report.qa = qaResult;

    // ── English gibberish cleanup ───────────────────────────────────────────
    // For English reports: strip Devanagari/Telugu script from non-mantra fields,
    // remove garbled character sequences, fix encoding artifacts.
    if (requestedLanguage === "en") {
      await updateJobStatus(supabaseAdmin, jobId!, "processing", "Cleaning report text", 94, "progress");
      report = cleanEnglishReport(report);
      console.log("🧹 [FINALIZE-JOB] English report gibberish cleanup complete");
    }

    // ── Localization + Language QC ──────────────────────────────────────────
    report = localizeStructuredReportTerms(report, requestedLanguage);
    report.language = requestedLanguage;
    report = stripAiDisclosure(report);

    const languageQc = useLanguagePipelineV2
      ? runLanguageQc(report, requestedLanguage)
      : {
          language: requestedLanguage,
          packVersion: activeLanguagePack.version,
          generationMode: "native" as const,
          passed: true,
          summary: { sectionsChecked: 0, sectionsPassed: 0, totalScriptChars: 0, totalLetters: 0, overallScriptRatio: 0, overallLatinRatio: 0 },
          sections: [],
          leakSamples: [],
        };

    report.languageQc = languageQc;
    report.languageQcPassed = languageQc.passed;
    report.failureCode = languageQc.passed ? null : "LANGUAGE_QC_FAILED";

    if (!languageQc.passed) {
      const leakSummary = languageQc.leakSamples
        .slice(0, 5)
        .map((s) => `${s.section}:${s.token}`)
        .join(", ");
      const ratioSummary = (languageQc.sections || [])
        .filter((s: any) => !s.passed)
        .slice(0, 5)
        .map((s: any) => `${s.section}:script=${(Number(s.scriptRatio || 0) * 100).toFixed(1)}%,latin=${(Number(s.latinRatio || 0) * 100).toFixed(1)}%`)
        .join(", ");
      console.warn(`\u26A0\uFE0F [FINALIZE-JOB] LANGUAGE_QC_FAILED (non-fatal): ${leakSummary || ratioSummary || "localized output validation did not pass"}`);
      report.errors = [...(report.errors || []), `LANGUAGE_QC_FAILED: ${leakSummary || ratioSummary || "localized output validation did not pass"}`];
    }

    // ── Chart Fetching ─────────────────────────────────────────────────────
    try {
      await updateJobStatus(supabaseAdmin, jobId!, "processing", "Fetching Kundali charts", 97, "progress");
      const charts = await fetchKundaliCharts(day, month, year, hour, min, job.latitude, job.longitude, job.timezone, requestedLanguage);
      report.charts = charts;
    } catch (chartErr) {
      console.warn("\u26A0\uFE0F [FINALIZE-JOB] Chart fetch failed (non-fatal):", chartErr);
      report.charts = [];
    }

    // ── Save completed report ──────────────────────────────────────────────
    report.tokensUsed = totalTokens;

    const extendedCompletion = await supabaseAdmin
      .from("kundli_report_jobs")
      .update({
        status: "completed",
        current_phase: "Complete",
        progress_percent: 100,
        report_data: report,
        generation_language_mode: useLanguagePipelineV2 ? "native" : "legacy",
        language_qc: report.languageQc || null,
        debug_summary: {
          languagePackVersion: activeLanguagePack.version,
          requestedLanguage,
          effectiveGenerationLanguage: effectiveGenLang,
          generationMode: useLanguagePipelineV2 ? "native" : "legacy",
          tokensUsed: totalTokens,
          qaScore: report.qa?.overallScore || null,
        },
        completed_at: new Date().toISOString(),
      })
      .eq("id", jobId);

    if (extendedCompletion.error) {
      console.warn("[FINALIZE-JOB] Extended completion update failed, using legacy payload:", extendedCompletion.error);
      await supabaseAdmin
        .from("kundli_report_jobs")
        .update({
          status: "completed",
          current_phase: "Complete",
          progress_percent: 100,
          report_data: report,
          completed_at: new Date().toISOString(),
        })
        .eq("id", jobId);
    }

    await createJobEvent(supabaseAdmin, {
      jobId: jobId!,
      phase: "Complete",
      eventType: "success",
      message: "Report generation completed",
      metrics: { progress: 100, tokensUsed: totalTokens },
    });

    await upsertKundliGeneratedReport(supabaseAdmin, {
      jobId: jobId!,
      language: requestedLanguage,
      generationMode: useLanguagePipelineV2 ? "native" : "legacy",
      status: "completed",
      reportSummary: {
        tokensUsed: totalTokens,
        qaScore: report.qa?.overallScore || null,
        errorCount: Array.isArray(report.errors) ? report.errors.length : 0,
        sections: {
          planets: Array.isArray(report.planets) ? report.planets.length : 0,
          houses: Array.isArray(report.houses) ? report.houses.length : 0,
        },
      },
    });

    console.log("\u2705 [FINALIZE-JOB] Report completed and saved successfully");
    return new Response(
      JSON.stringify({ success: true, jobId }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("\u274C [FINALIZE-JOB] Error:", error);

    if (jobId) {
      await createJobEvent(supabaseAdmin, {
        jobId,
        phase: "Finalize Error",
        eventType: "fail",
        message: error instanceof Error ? error.message : "Unknown error",
      });

      await supabaseAdmin
        .from("kundli_report_jobs")
        .update({
          status: "failed",
          failure_code: "FINALIZE_ERROR",
          error_message: error instanceof Error ? error.message : "Unknown error",
        })
        .eq("id", jobId)
        .then(({ error: updateErr }) => {
          if (updateErr) {
            return supabaseAdmin
              .from("kundli_report_jobs")
              .update({
                status: "failed",
                error_message: error instanceof Error ? error.message : "Unknown error",
              })
              .eq("id", jobId);
          }
        });
    }

    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});

async function updateJobStatus(
  supabase: any,
  jobId: string,
  status: string,
  phase: string,
  progress: number,
  eventType: "start" | "progress" | "success" | "fail" | "info" = "progress",
) {
  const withHeartbeat = await supabase
    .from("kundli_report_jobs")
    .update({
      status,
      current_phase: phase,
      progress_percent: progress,
      heartbeat_at: new Date().toISOString(),
    })
    .eq("id", jobId);
  if (withHeartbeat.error) {
    await supabase
      .from("kundli_report_jobs")
      .update({ status, current_phase: phase, progress_percent: progress })
      .eq("id", jobId);
  }

  await createJobEvent(supabase, {
    jobId,
    phase,
    eventType,
    message: `${status}: ${phase}`,
    metrics: { progress },
  });
}
