/**
 * finalize-kundli-report — Stage 3 of the Kundli pipeline.
 *
 * Runs QA validation, localization, language QC, chart fetching, and saves
 * the completed report. Triggered by translate-kundli-report after the
 * translation sweep is done.
 *
 * Flow:  process-kundli-job → translate-kundli-report → [this]
 */

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.80.0";

import { runQAValidation, sanitizeReportContent } from "../_shared/generate-kundli-report/qa-agent.ts";
import { setAgentLanguageContext } from "../_shared/generate-kundli-report/agent-base.ts";
import { getLanguagePack, normalizeLanguage } from "../_shared/language-packs/index.ts";
import { runLanguageQc } from "../_shared/language-qc.ts";
import type { SupportedLanguage } from "../_shared/language-packs/types.ts";
import { createJobEvent, touchJobHeartbeat } from "../_shared/job-events.ts";
import { localizeStructuredReportTerms } from "../_shared/language-localize.ts";
import { upsertKundliGeneratedReport } from "../_shared/kundli-audit.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function isLanguagePipelineV2Enabled(language: SupportedLanguage): boolean {
  if (language === "hi" || language === "te" || language === "kn" || language === "mr" || language === "ta" || language === "gu") return true;
  if (language === "en") return false;
  return false;
}

function parseBirthTime(rawTime: string): { hour: number; min: number } {
  const input = String(rawTime || "").trim();
  if (!input) throw new Error("Invalid birth time: empty");
  const ampm = input.match(/\b(am|pm)\b/i)?.[1]?.toLowerCase();
  const cleaned = input.replace(/\s*(am|pm)\s*/i, "");
  const parts = cleaned.split(":").map((x) => Number(x));
  let hour = parts[0];
  const min = parts.length > 1 ? parts[1] : 0;
  if (!Number.isFinite(hour) || !Number.isFinite(min)) {
    throw new Error(`Invalid birth time format: "${rawTime}"`);
  }
  if (ampm) {
    hour = hour % 12;
    if (ampm === "pm") hour += 12;
  }
  return { hour, min };
}

function stripAiDisclosure<T>(value: T): T {
  const cleanText = (text: string): string =>
    text
      .replace(/\bAI[- ]generated\b/gi, "generated")
      .replace(/\bgenerated by AI\b/gi, "generated")
      .replace(/\bAI[- ]powered\b/gi, "")
      .replace(/\bartificial intelligence\b/gi, "")
      .replace(/[ \t]{2,}/g, " ")
      .trim();

  if (typeof value === "string") return cleanText(value) as T;
  if (Array.isArray(value)) return value.map((item) => stripAiDisclosure(item)) as T;
  if (value && typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(obj)) out[key] = stripAiDisclosure(val);
    return out as T;
  }
  return value;
}

// ── Report text cleanup ──────────────────────────────────────────────────────

/**
 * Detect whether a string is mostly gibberish.
 * Returns true if the text has hallmarks of AI-garbled output.
 */
function isGibberishText(text: string): boolean {
  if (!text || text.length < 10) return false;

  // 1. Excessive consecutive consonants (no language has 6+ consonants in a row)
  if (/[bcdfghjklmnpqrstvwxyz]{6,}/i.test(text)) return true;

  // 2. Same character repeated 4+ times
  if (/(.)\1{3,}/.test(text)) return true;

  // 3. Mostly non-ASCII non-Devanagari/Telugu/Kannada control/garbage characters
  const controlChars = text.replace(/[\x20-\x7E\u0900-\u097F\u0C00-\u0CFF\n\r\t]/g, "");
  if (controlChars.length > text.length * 0.3) return true;

  return false;
}

/**
 * Clean a single text string — language-agnostic:
 *  - Remove zero-width / invisible Unicode
 *  - Collapse repeated characters (4+ → 2)
 *  - Collapse excess whitespace
 *  - Replace em-dashes (—) with regular dashes (-) to avoid AI-generated look
 *
 * NOTE: We do NOT strip Devanagari/Telugu from English reports. If the content
 * is valid (e.g., Sanskrit terms), we keep it. Only truly garbled sequences
 * (detected by isGibberishText) get flagged.
 */
function cleanReportText(text: string): string {
  if (!text || typeof text !== "string") return text;

  let cleaned = text;

  // Remove zero-width chars, soft hyphens, and other invisible Unicode
  cleaned = cleaned.replace(/[\u200B-\u200F\u2028-\u202F\u00AD\uFEFF]/g, "");

  // Replace em-dashes (—) with regular dashes (-) — avoids AI-generated look
  cleaned = cleaned.replace(/\u2014/g, "-");
  // Replace en-dashes (–) with regular dashes too
  cleaned = cleaned.replace(/\u2013/g, "-");

  // Remove same character repeated 4+ times (garbled output)
  cleaned = cleaned.replace(/(.)\1{3,}/g, "$1$1");

  // Collapse multiple spaces / newlines
  cleaned = cleaned.replace(/[ \t]{2,}/g, " ").replace(/\n{3,}/g, "\n\n").trim();

  return cleaned;
}

/**
 * Recursively clean all text fields in the report (any language).
 * Replaces em-dashes, removes invisible chars, fixes garbled sequences.
 * Does NOT remove valid script content (Devanagari, Telugu, Kannada, Latin).
 */
function cleanReportTexts<T>(value: T, parentKey = ""): T {
  if (typeof value === "string") {
    // If the entire string is true gibberish, return empty
    if (isGibberishText(value)) {
      const cleaned = cleanReportText(value);
      if (cleaned.length < 5) return "" as unknown as T;
      return cleaned as unknown as T;
    }
    return cleanReportText(value) as unknown as T;
  }
  if (Array.isArray(value)) {
    return value
      .map((item) => cleanReportTexts(item, parentKey))
      .filter((item) => {
        if (typeof item === "string" && item.trim() === "") return false;
        return true;
      }) as unknown as T;
  }
  if (value && typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(obj)) {
      out[key] = cleanReportTexts(val, key);
    }
    return out as T;
  }
  return value;
}

// ── Chart SVG fetching ──────────────────────────────────────────────────────

function localizeChartSvgText(svg: string, language: string): string {
  if (language === "hi" || language === "te" || language === "kn" || language === "mr" || language === "ta" || language === "gu") return svg;
  const replacements: [string, string][] = [
    ["\u0936\u0941", "VE"], ["\u092C\u0941", "ME"], ["\u092E\u0902", "MA"],
    ["\u091A\u0902", "MO"], ["\u0938\u0942", "SU"], ["\u0917\u0941", "JU"],
    ["\u0930\u093E", "RA"], ["\u0915\u0947", "KE"], ["\u0936", "SA"],
  ];
  let result = svg;
  for (const [hindi, eng] of replacements) {
    result = result.replaceAll(hindi, eng);
  }
  return result;
}

const PDF_CHART_TYPES = ["D1","D2","D3","D4","D7","D9","D10","D12","D20","D24","D27","D60"] as const;

const CHART_INFO: Record<string, { name: string; nameHindi: string; nameKannada: string; nameMarathi: string; purpose: string }> = {
  D1:  { name: "Rashi (Birth Chart)",       nameHindi: "\u0930\u093E\u0936\u093F \u091A\u0915\u094D\u0930",         nameKannada: "\u0C9C\u0CA8\u0CCD\u0CAE \u0C95\u0CC1\u0C82\u0CA1\u0CB2\u0CBF",         nameMarathi: "\u091C\u0928\u094D\u092E \u0915\u0941\u0902\u0921\u0932\u0940",         purpose: "Overall life assessment" },
  D2:  { name: "Hora",                      nameHindi: "\u0939\u094B\u0930\u093E",               nameKannada: "\u0CB9\u0CCB\u0CB0\u0CBE \u0C95\u0CC1\u0C82\u0CA1\u0CB2\u0CBF",         nameMarathi: "\u0939\u094B\u0930\u093E \u0915\u0941\u0902\u0921\u0932\u0940",         purpose: "Wealth and finances" },
  D3:  { name: "Drekkana",                  nameHindi: "\u0926\u094D\u0930\u0947\u0915\u094D\u0915\u093E\u0923",          nameKannada: "\u0CA6\u0CCD\u0CB0\u0CC7\u0C95\u0CCD\u0C95\u0CBE\u0CA3 \u0C95\u0CC1\u0C82\u0CA1\u0CB2\u0CBF",     nameMarathi: "\u0926\u094D\u0930\u0947\u0915\u094D\u0915\u093E\u0923 \u0915\u0941\u0902\u0921\u0932\u0940",     purpose: "Siblings and courage" },
  D4:  { name: "Chaturthamsa",              nameHindi: "\u091A\u0924\u0941\u0930\u094D\u0925\u093E\u0902\u0936",          nameKannada: "\u0C9A\u0CA4\u0CC1\u0CB0\u0CCD\u0CA5\u0CBE\u0C82\u0CB6 \u0C95\u0CC1\u0C82\u0CA1\u0CB2\u0CBF",     nameMarathi: "\u091A\u0924\u0941\u0930\u094D\u0925\u093E\u0902\u0936 \u0915\u0941\u0902\u0921\u0932\u0940",     purpose: "Fortune and property" },
  D7:  { name: "Saptamsa",                  nameHindi: "\u0938\u092A\u094D\u0924\u093E\u0902\u0936",            nameKannada: "\u0CB8\u0CAA\u0CCD\u0CA4\u0CBE\u0C82\u0CB6 \u0C95\u0CC1\u0C82\u0CA1\u0CB2\u0CBF",       nameMarathi: "\u0938\u092A\u094D\u0924\u093E\u0902\u0936 \u0915\u0941\u0902\u0921\u0932\u0940",       purpose: "Children and progeny" },
  D9:  { name: "Navamsa",                   nameHindi: "\u0928\u0935\u093E\u0902\u0936",              nameKannada: "\u0CA8\u0CB5\u0CBE\u0C82\u0CB6 \u0C95\u0CC1\u0C82\u0CA1\u0CB2\u0CBF",         nameMarathi: "\u0928\u0935\u093E\u0902\u0936 \u0915\u0941\u0902\u0921\u0932\u0940",         purpose: "Marriage and spouse" },
  D10: { name: "Dasamsa",                   nameHindi: "\u0926\u0936\u093E\u0902\u0936",              nameKannada: "\u0CA6\u0CB6\u0CBE\u0C82\u0CB6 \u0C95\u0CC1\u0C82\u0CA1\u0CB2\u0CBF",         nameMarathi: "\u0926\u0936\u093E\u0902\u0936 \u0915\u0941\u0902\u0921\u0932\u0940",         purpose: "Career and profession" },
  D12: { name: "Dwadasamsa",                nameHindi: "\u0926\u094D\u0935\u093E\u0926\u0936\u093E\u0902\u0936",          nameKannada: "\u0CA6\u0CCD\u0CB5\u0CBE\u0CA6\u0CB6\u0CBE\u0C82\u0CB6 \u0C95\u0CC1\u0C82\u0CA1\u0CB2\u0CBF",     nameMarathi: "\u0926\u094D\u0935\u093E\u0926\u0936\u093E\u0902\u0936 \u0915\u0941\u0902\u0921\u0932\u0940",     purpose: "Parents and ancestry" },
  D20: { name: "Vimsamsa",                  nameHindi: "\u0935\u093F\u0902\u0936\u093E\u0902\u0936",            nameKannada: "\u0CB5\u0CBF\u0C82\u0CB6\u0CBE\u0C82\u0CB6 \u0C95\u0CC1\u0C82\u0CA1\u0CB2\u0CBF",       nameMarathi: "\u0935\u093F\u0902\u0936\u093E\u0902\u0936 \u0915\u0941\u0902\u0921\u0932\u0940",       purpose: "Spiritual progress" },
  D24: { name: "Chaturvimsamsa",            nameHindi: "\u091A\u0924\u0941\u0930\u094D\u0935\u093F\u0902\u0936\u093E\u0902\u0936",       nameKannada: "\u0C9A\u0CA4\u0CC1\u0CB0\u0CCD\u0CB5\u0CBF\u0C82\u0CB6\u0CBE\u0C82\u0CB6 \u0C95\u0CC1\u0C82\u0CA1\u0CB2\u0CBF", nameMarathi: "\u091A\u0924\u0941\u0930\u094D\u0935\u093F\u0902\u0936\u093E\u0902\u0936 \u0915\u0941\u0902\u0921\u0932\u0940", purpose: "Education and learning" },
  D27: { name: "Bhamsa",                    nameHindi: "\u092D\u093E\u0902\u0936",               nameKannada: "\u0CB8\u0CAA\u0CCD\u0CA4\u0CB5\u0CBF\u0C82\u0CB6\u0CBE\u0C82\u0CB6 \u0C95\u0CC1\u0C82\u0CA1\u0CB2\u0CBF",   nameMarathi: "\u0938\u092A\u094D\u0924\u0935\u093F\u0902\u0936\u093E\u0902\u0936 \u0915\u0941\u0902\u0921\u0932\u0940",   purpose: "Strength and weakness" },
  D60: { name: "Shashtiamsa",               nameHindi: "\u0937\u0937\u094D\u091F\u094D\u092F\u0902\u0936",           nameKannada: "\u0CB7\u0CB7\u0CCD\u0C9F\u0CCD\u0CAF\u0C82\u0CB6 \u0C95\u0CC1\u0C82\u0CA1\u0CB2\u0CBF",       nameMarathi: "\u0937\u0937\u094D\u091F\u094D\u092F\u0902\u0936 \u0915\u0941\u0902\u0921\u0932\u0940",       purpose: "Past life karma" },
};

async function fetchOneChartSvg(
  chartType: string,
  payload: Record<string, unknown>,
): Promise<string | null> {
  try {
    const res = await fetch(
      `https://api-sbox.a4b.io/gw2/seer/external/v1/chart/horo-image/${chartType}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json", "x-fe-server": "true", "x-afb-r-uid": "7160881" },
        body: JSON.stringify(payload),
      }
    );
    if (!res.ok) { console.warn(`\u26A0\uFE0F [CHARTS] ${chartType} HTTP ${res.status}`); return null; }
    const data = await res.json();
    return (data?.data?.svg as string) || null;
  } catch (err) {
    console.warn(`\u26A0\uFE0F [CHARTS] ${chartType} fetch error:`, err);
    return null;
  }
}

async function fetchKundaliCharts(
  day: number, month: number, year: number,
  hour: number, minute: number,
  lat: number, lon: number, tzone: number,
  language: string = "en",
): Promise<Array<{ type: string; name: string; nameHindi: string; purpose: string; svg: string }>> {
  const payload = { day, month, year, hour, minute, lat, lon, tzone, chartType: "North", image_type: "svg", language };
  const results = await Promise.allSettled(
    PDF_CHART_TYPES.map(async (ct) => {
      const rawSvg = await fetchOneChartSvg(ct, payload);
      if (!rawSvg) throw new Error("no svg");
      const svg = localizeChartSvgText(rawSvg, language);
      return { type: ct, svg, ...CHART_INFO[ct] };
    })
  );
  const charts = results
    .filter((r): r is PromiseFulfilledResult<any> => r.status === "fulfilled")
    .map((r) => r.value);
  console.log(`\uD83D\uDCCA [CHARTS] Fetched ${charts.length}/${PDF_CHART_TYPES.length} chart SVGs`);
  return charts;
}

// ── QA with timeout ─────────────────────────────────────────────────────────

async function runQaWithTimeout(report: Record<string, any>, timeoutMs = 45000): Promise<any> {
  const timeoutFallback = {
    issues: [{
      section: "qa", severity: "warning", issueType: "timeout",
      description: `QA validation exceeded ${timeoutMs}ms and returned fallback validation.`,
      suggestedFix: "Review this report manually if strict QA verification is required.",
    }],
    blockedContent: [],
    overallScore: 7,
    approved: true,
  };
  try {
    const result = await Promise.race([
      runQAValidation(report),
      new Promise<any>((resolve) => setTimeout(() => resolve(timeoutFallback), timeoutMs)),
    ]);
    return result || timeoutFallback;
  } catch {
    return timeoutFallback;
  }
}

// ── Main handler ────────────────────────────────────────────────────────────

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const supabaseAdmin = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
  );

  let jobId: string | undefined;

  try {
    const body = await req.json();
    jobId = body.jobId;
    console.log(`\uD83C\uDFC1 [FINALIZE-JOB] Starting finalization for job: ${jobId}`);

    // Load job record with translated report
    const { data: job, error: fetchError } = await supabaseAdmin
      .from("kundli_report_jobs")
      .select("*")
      .eq("id", jobId)
      .single();

    if (fetchError || !job) {
      console.error("\u274C [FINALIZE-JOB] Job not found:", jobId);
      return new Response(JSON.stringify({ error: "Job not found" }), { status: 404 });
    }

    let report = job.report_data as Record<string, any>;
    if (!report) {
      const nowIso = new Date().toISOString();
      const existingDebugSummary =
        job.debug_summary && typeof job.debug_summary === "object"
          ? { ...(job.debug_summary as Record<string, any>) }
          : {};
      const priorRequeueAttempts = Number(existingDebugSummary.missingReportDataRequeueAttempts || 0);
      const canRequeueTranslation = priorRequeueAttempts < 1;
      const waitingPhase = canRequeueTranslation
        ? "Waiting for report data — requeueing translation"
        : "Waiting for report data — awaiting prior stage";

      existingDebugSummary.missingReportDataRequeueAttempts = canRequeueTranslation
        ? priorRequeueAttempts + 1
        : priorRequeueAttempts;
      existingDebugSummary.lastMissingReportDataAt = nowIso;
      existingDebugSummary.lastMissingReportDataPhase = String(job.current_phase || "");

      const nextProgress = Math.max(Number(job.progress_percent || 0), 85);

      const { error: waitingUpdateError } = await supabaseAdmin
        .from("kundli_report_jobs")
        .update({
          status: "processing",
          current_phase: waitingPhase,
          progress_percent: nextProgress,
          heartbeat_at: nowIso,
          debug_summary: existingDebugSummary,
        })
        .eq("id", jobId);
      if (waitingUpdateError) {
        console.warn("[FINALIZE-JOB] Failed to mark waiting state for missing report_data:", waitingUpdateError.message);
      }

      await createJobEvent(supabaseAdmin, {
        jobId,
        phase: "Finalize waiting for report_data",
        eventType: "info",
        message: canRequeueTranslation
          ? "Missing report_data in finalize; requeued translation stage once"
          : "Missing report_data in finalize; requeue limit reached",
        metrics: { progress: nextProgress, requeueAttempt: priorRequeueAttempts + (canRequeueTranslation ? 1 : 0) },
      });

      if (canRequeueTranslation) {
        const stage2Url = `${Deno.env.get("SUPABASE_URL")}/functions/v1/translate-kundli-report`;
        const stage2Promise = fetch(stage2Url, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")}`,
          },
          body: JSON.stringify({ jobId }),
        }).catch((err) => {
          console.error("[FINALIZE-JOB] Failed to requeue translation stage:", err);
        });

        // @ts-ignore - EdgeRuntime is available in Supabase Edge Functions
        if (typeof EdgeRuntime !== "undefined" && EdgeRuntime.waitUntil) {
          // @ts-ignore
          EdgeRuntime.waitUntil(stage2Promise);
        }
      }

      return new Response(
        JSON.stringify({
          success: true,
          accepted: true,
          waitingForReportData: true,
          requeued: canRequeueTranslation,
          jobId,
        }),
        {
          status: 202,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    const requestedLanguage = normalizeLanguage(job.language || "en");
    const useLanguagePipelineV2 = isLanguagePipelineV2Enabled(requestedLanguage);
    const effectiveGenLang: SupportedLanguage = useLanguagePipelineV2 ? requestedLanguage : "en";
    const activeLanguagePack = getLanguagePack(requestedLanguage);
    setAgentLanguageContext(effectiveGenLang);

    let totalTokens = report.tokensUsed || 0;
    const [year, month, day] = String(job.date_of_birth).split("-").map(Number);
    const { hour: localHour, min: localMin } = parseBirthTime(String(job.time_of_birth));

    // Convert birth time from local timezone to IST (UTC+5:30) for chart API
    // Seer chart API expects IST time (tzone field is ignored)
    const istOffsetMinutes = 5.5 * 60; // IST is UTC+5:30
    const localOffsetMinutes = (job.timezone || 0) * 60; // Local timezone offset in minutes
    const offsetDiffMinutes = istOffsetMinutes - localOffsetMinutes;

    let istHour = localHour;
    let istMin = localMin + offsetDiffMinutes;
    let istYear = year, istMonth = month, istDay = day;

    if (istMin >= 60) {
      istHour += Math.floor(istMin / 60);
      istMin = istMin % 60;
    } else if (istMin < 0) {
      istHour += Math.floor(istMin / 60);
      istMin = istMin % 60;
      if (istMin < 0) istMin += 60;
    }

    if (istHour >= 24) {
      istHour -= 24;
      const nextDay = new Date(year, month - 1, day + 1);
      istYear = nextDay.getFullYear();
      istMonth = nextDay.getMonth() + 1;
      istDay = nextDay.getDate();
    } else if (istHour < 0) {
      istHour += 24;
      const prevDay = new Date(year, month - 1, day - 1);
      istYear = prevDay.getFullYear();
      istMonth = prevDay.getMonth() + 1;
      istDay = prevDay.getDate();
    }

    // ── QA Validation ──────────────────────────────────────────────────────
    await updateJobStatus(supabaseAdmin, jobId!, "processing", "Running quality checks", 92, "progress");
    const qaResult = await runQaWithTimeout(report);
    if (qaResult.blockedContent.length > 0 || qaResult.issues.some((i: any) => i.severity === "critical")) {
      report = sanitizeReportContent(report);
    }
    report.qa = qaResult;

    // ── Text cleanup (ALL languages) ──────────────────────────────────────────
    // Remove em-dashes (→ regular dashes), invisible chars, garbled sequences.
    // Applied to ALL languages — does NOT strip valid script content.
    await updateJobStatus(supabaseAdmin, jobId!, "processing", "Cleaning report text", 94, "progress");
    report = cleanReportTexts(report);
    console.log("🧹 [FINALIZE-JOB] Report text cleanup complete (em-dashes, invisible chars, gibberish)");

    // ── Localization + Language QC ──────────────────────────────────────────
    report = localizeStructuredReportTerms(report, requestedLanguage);
    report.language = requestedLanguage;
    report = stripAiDisclosure(report);

    const languageQc = useLanguagePipelineV2
      ? runLanguageQc(report, requestedLanguage)
      : {
          language: requestedLanguage,
          packVersion: activeLanguagePack.version,
          generationMode: "native" as const,
          passed: true,
          summary: { sectionsChecked: 0, sectionsPassed: 0, totalScriptChars: 0, totalLetters: 0, overallScriptRatio: 0, overallLatinRatio: 0 },
          sections: [],
          leakSamples: [],
        };

    report.languageQc = languageQc;
    report.languageQcPassed = languageQc.passed;
    report.failureCode = languageQc.passed ? null : "LANGUAGE_QC_FAILED";

    if (!languageQc.passed) {
      const leakSummary = languageQc.leakSamples
        .slice(0, 5)
        .map((s) => `${s.section}:${s.token}`)
        .join(", ");
      const ratioSummary = (languageQc.sections || [])
        .filter((s: any) => !s.passed)
        .slice(0, 5)
        .map((s: any) => `${s.section}:script=${(Number(s.scriptRatio || 0) * 100).toFixed(1)}%,latin=${(Number(s.latinRatio || 0) * 100).toFixed(1)}%`)
        .join(", ");
      console.warn(`\u26A0\uFE0F [FINALIZE-JOB] LANGUAGE_QC_FAILED (non-fatal): ${leakSummary || ratioSummary || "localized output validation did not pass"}`);
      report.errors = [...(report.errors || []), `LANGUAGE_QC_FAILED: ${leakSummary || ratioSummary || "localized output validation did not pass"}`];
    }

    // ── Chart Fetching ─────────────────────────────────────────────────────
    try {
      await updateJobStatus(supabaseAdmin, jobId!, "processing", "Fetching Kundali charts", 97, "progress");
      const charts = await fetchKundaliCharts(istDay, istMonth, istYear, istHour, Math.floor(istMin), job.latitude, job.longitude, 5.5, requestedLanguage);
      report.charts = charts;
    } catch (chartErr) {
      console.warn("\u26A0\uFE0F [FINALIZE-JOB] Chart fetch failed (non-fatal):", chartErr);
      report.charts = [];
    }

    // ── Save completed report ──────────────────────────────────────────────
    report.tokensUsed = totalTokens;

    const extendedCompletion = await supabaseAdmin
      .from("kundli_report_jobs")
      .update({
        status: "completed",
        current_phase: "Complete",
        progress_percent: 100,
        report_data: report,
        generation_language_mode: useLanguagePipelineV2 ? "native" : "legacy",
        language_qc: report.languageQc || null,
        debug_summary: {
          languagePackVersion: activeLanguagePack.version,
          requestedLanguage,
          effectiveGenerationLanguage: effectiveGenLang,
          generationMode: useLanguagePipelineV2 ? "native" : "legacy",
          tokensUsed: totalTokens,
          qaScore: report.qa?.overallScore || null,
        },
        completed_at: new Date().toISOString(),
      })
      .eq("id", jobId);

    if (extendedCompletion.error) {
      console.warn("[FINALIZE-JOB] Extended completion update failed, using legacy payload:", extendedCompletion.error);
      await supabaseAdmin
        .from("kundli_report_jobs")
        .update({
          status: "completed",
          current_phase: "Complete",
          progress_percent: 100,
          report_data: report,
          completed_at: new Date().toISOString(),
        })
        .eq("id", jobId);
    }

    await createJobEvent(supabaseAdmin, {
      jobId: jobId!,
      phase: "Complete",
      eventType: "success",
      message: "Report generation completed",
      metrics: { progress: 100, tokensUsed: totalTokens },
    });

    await upsertKundliGeneratedReport(supabaseAdmin, {
      jobId: jobId!,
      language: requestedLanguage,
      generationMode: useLanguagePipelineV2 ? "native" : "legacy",
      status: "completed",
      reportSummary: {
        tokensUsed: totalTokens,
        qaScore: report.qa?.overallScore || null,
        errorCount: Array.isArray(report.errors) ? report.errors.length : 0,
        sections: {
          planets: Array.isArray(report.planets) ? report.planets.length : 0,
          houses: Array.isArray(report.houses) ? report.houses.length : 0,
        },
      },
    });

    console.log("\u2705 [FINALIZE-JOB] Report completed and saved successfully");
    return new Response(
      JSON.stringify({ success: true, jobId }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("\u274C [FINALIZE-JOB] Error:", error);

    if (jobId) {
      await createJobEvent(supabaseAdmin, {
        jobId,
        phase: "Finalize Error",
        eventType: "fail",
        message: error instanceof Error ? error.message : "Unknown error",
      });

      await supabaseAdmin
        .from("kundli_report_jobs")
        .update({
          status: "failed",
          failure_code: "FINALIZE_ERROR",
          error_message: error instanceof Error ? error.message : "Unknown error",
        })
        .eq("id", jobId)
        .then(({ error: updateErr }) => {
          if (updateErr) {
            return supabaseAdmin
              .from("kundli_report_jobs")
              .update({
                status: "failed",
                error_message: error instanceof Error ? error.message : "Unknown error",
              })
              .eq("id", jobId);
          }
        });
    }

    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});

async function updateJobStatus(
  supabase: any,
  jobId: string,
  status: string,
  phase: string,
  progress: number,
  eventType: "start" | "progress" | "success" | "fail" | "info" = "progress",
) {
  const withHeartbeat = await supabase
    .from("kundli_report_jobs")
    .update({
      status,
      current_phase: phase,
      progress_percent: progress,
      heartbeat_at: new Date().toISOString(),
    })
    .eq("id", jobId);
  if (withHeartbeat.error) {
    await supabase
      .from("kundli_report_jobs")
      .update({ status, current_phase: phase, progress_percent: progress })
      .eq("id", jobId);
  }

  await createJobEvent(supabase, {
    jobId,
    phase,
    eventType,
    message: `${status}: ${phase}`,
    metrics: { progress },
  });
}
