export const KN_TERM_MAPS = {
  planets: {
    Sun: "ಸೂರ್ಯ", Moon: "ಚಂದ್ರ", Mars: "ಮಂಗಳ", Mercury: "ಬುಧ", Jupiter: "ಗುರು", Venus: "ಶುಕ್ರ", Saturn: "ಶನಿ", Rahu: "ರಾಹು", Ketu: "ಕೇತು",
  },
  signs: {
    Aries: "ಮೇಷ", Taurus: "ವೃಷಭ", Gemini: "ಮಿಥುನ", Cancer: "ಕರ್ಕ", Leo: "ಸಿಂಹ", Virgo: "ಕನ್ಯಾ", Libra: "ತುಲಾ", Scorpio: "ವೃಶ್ಚಿಕ", Sagittarius: "ಧನು", Capricorn: "ಮಕರ", Aquarius: "ಕುಂಭ", Pisces: "ಮೀನ",
  },
  weekdays: {
    Sunday: "ಭಾನುವಾರ", Monday: "ಸೋಮವಾರ", Tuesday: "ಮಂಗಳವಾರ", Wednesday: "ಬುಧವಾರ", Thursday: "ಗುರುವಾರ", Friday: "ಶುಕ್ರವಾರ", Saturday: "ಶನಿವಾರ",
  },
  houses: {
    "1": "ಪ್ರಥಮ ಭಾವ", "2": "ದ್ವಿತೀಯ ಭಾವ", "3": "ತೃತೀಯ ಭಾವ", "4": "ಚತುರ್ಥ ಭಾವ", "5": "ಪಂಚಮ ಭಾವ", "6": "ಷಷ್ಠ ಭಾವ", "7": "ಸಪ್ತಮ ಭಾವ", "8": "ಅಷ್ಟಮ ಭಾವ", "9": "ನವಮ ಭಾವ", "10": "ದಶಮ ಭಾವ", "11": "ಏಕಾದಶ ಭಾವ", "12": "ದ್ವಾದಶ ಭಾವ",
  },
  nakshatras: {
    Ashwini: "ಅಶ್ವಿನಿ",
    Bharani: "ಭರಣಿ",
    Krittika: "ಕೃತ್ತಿಕಾ",
    Rohini: "ರೋಹಿಣಿ",
    Mrigashira: "ಮೃಗಶಿರಾ",
    Ardra: "ಆರ್ದ್ರಾ",
    Punarvasu: "ಪುನರ್ವಸು",
    Pushya: "ಪುಷ್ಯ",
    Ashlesha: "ಆಶ್ಲೇಷಾ",
    Magha: "ಮಘಾ",
    "Purva Phalguni": "ಪೂರ್ವ ಫಲ್ಗುಣಿ",
    "Uttara Phalguni": "ಉತ್ತರ ಫಲ್ಗುಣಿ",
    Hasta: "ಹಸ್ತ",
    Chitra: "ಚಿತ್ರಾ",
    Swati: "ಸ್ವಾತಿ",
    Vishakha: "ವಿಶಾಖಾ",
    Anuradha: "ಅನುರಾಧಾ",
    Jyeshtha: "ಜ್ಯೇಷ್ಠಾ",
    Mula: "ಮೂಲ",
    "Purva Ashadha": "ಪೂರ್ವಾಷಾಢ",
    "Uttara Ashadha": "ಉತ್ತರಾಷಾಢ",
    Shravana: "ಶ್ರವಣ",
    Dhanishta: "ಧನಿಷ್ಠಾ",
    Shatabhisha: "ಶತಭಿಷಾ",
    "Purva Bhadrapada": "ಪೂರ್ವ ಭಾದ್ರಪದ",
    "Uttara Bhadrapada": "ಉತ್ತರ ಭಾದ್ರಪದ",
    Revati: "ರೇವತಿ",
  },
  months: {
    January: "ಜನವರಿ",
    February: "ಫೆಬ್ರವರಿ",
    March: "ಮಾರ್ಚ್",
    April: "ಏಪ್ರಿಲ್",
    May: "ಮೇ",
    June: "ಜೂನ್",
    July: "ಜುಲೈ",
    August: "ಆಗಸ್ಟ್",
    September: "ಸೆಪ್ಟೆಂಬರ್",
    October: "ಅಕ್ಟೋಬರ್",
    November: "ನವೆಂಬರ್",
    December: "ಡಿಸೆಂಬರ್",
  },
  misc: {
    Mahadasha: "ಮಹಾದಶೆ",
    Antardasha: "ಅಂತರ್ದಶೆ",
    "Sade Sati": "ಸಾಡೆ ಸಾತಿ",
    "Not Active": "ಸಕ್ರಿಯವಲ್ಲ",
    "Rising Phase": "ಆರಂಭಿಕ ಹಂತ",
    "Peak Phase": "ಉತ್ತುಂಗ ಹಂತ",
    "Setting Phase": "ಅಂತಿಮ ಹಂತ",
    Ascendant: "ಲಗ್ನ",
    "Moon Sign": "ಚಂದ್ರ ರಾಶಿ",
    "Birth Nakshatra": "ಜನ್ಮ ನಕ್ಷತ್ರ",
    "Planetary Positions": "ಗ್ರಹ ಸ್ಥಾನಗಳು",
    "House Analysis": "ಭಾವ ವಿಶ್ಲೇಷಣೆ",
    "Career Analysis": "ವೃತ್ತಿ ವಿಶ್ಲೇಷಣೆ",
    "Marriage Analysis": "ವಿವಾಹ ವಿಶ್ಲೇಷಣೆ",
    "Health Guidance": "ಆರೋಗ್ಯ ಮಾರ್ಗದರ್ಶನ",
    house: "ಭಾವ",
    houses: "ಭಾವಗಳು",
    sign: "ರಾಶಿ",
    signs: "ರಾಶಿಗಳು",
    marriage: "ವಿವಾಹ",
    career: "ವೃತ್ತಿ",
    health: "ಆರೋಗ್ಯ",
    guidance: "ಮಾರ್ಗದರ್ಶನ",
    analysis: "ವಿಶ್ಲೇಷಣೆ",
    phase: "ಹಂತ",
    active: "ಸಕ್ರಿಯ",
    current: "ಪ್ರಸ್ತುತ",
    period: "ಅವಧಿ",
    prediction: "ಭವಿಷ್ಯವಾಣಿ",
    remedy: "ಪರಿಹಾರ",
    present: "ಇದೆ",
    absent: "ಇಲ್ಲ",
    nullified: "ನಿವಾರಿತ",
    partial: "ಭಾಗಶಃ",
    high: "ಉಚ್ಚ",
    medium: "ಮಧ್ಯಮ",
    low: "ಕಡಿಮೆ",
    none: "ಇಲ್ಲ",
    strong: "ಬಲವಾದ",
    weak: "ದುರ್ಬಲ",
    moderate: "ಮಧ್ಯಮ",
    male: "ಪುರುಷ",
    female: "ಮಹಿಳೆ",
    spouse: "ಜೀವನಸಂಗಾತಿ",
    partner: "ಸಂಗಾತಿ",
    years: "ವರ್ಷಗಳು",
    year: "ವರ್ಷ",
    months: "ತಿಂಗಳುಗಳು",
    month: "ತಿಂಗಳು",
    Siddha: "ಸಿದ್ಧ",
    Mangala: "ಮಂಗಳ",
    Pingala: "ಪಿಂಗಳ",
    Dhanya: "ಧನ್ಯ",
    Bhramari: "ಭ್ರಮರಿ",
    Bhadrika: "ಭದ್ರಿಕಾ",
    Ulka: "ಉಲ್ಕಾ",
    Sankata: "ಸಂಕಟ",
    Debilitated: "ನೀಚ",
    Exaltation: "ಉಚ್ಚ",
    Retrograde: "ವಕ್ರ",
  },
};
