export const MR_TERM_MAPS = {
  planets: {
    Sun: "सूर्य", Moon: "चंद्र", Mars: "मंगळ", Mercury: "बुध", Jupiter: "गुरू", Venus: "शुक्र", Saturn: "शनि", Rahu: "राहू", Ketu: "केतू",
  },
  signs: {
    Aries: "मेष", Taurus: "वृषभ", Gemini: "मिथुन", Cancer: "कर्क", Leo: "सिंह", Virgo: "कन्या", Libra: "तूळ", Scorpio: "वृश्चिक", Sagittarius: "धनु", Capricorn: "मकर", Aquarius: "कुंभ", Pisces: "मीन",
  },
  weekdays: {
    Sunday: "रविवार", Monday: "सोमवार", Tuesday: "मंगळवार", Wednesday: "बुधवार", Thursday: "गुरुवार", Friday: "शुक्रवार", Saturday: "शनिवार",
  },
  houses: {
    "1": "प्रथम भाव", "2": "द्वितीय भाव", "3": "तृतीय भाव", "4": "चतुर्थ भाव", "5": "पंचम भाव", "6": "षष्ठ भाव", "7": "सप्तम भाव", "8": "अष्टम भाव", "9": "नवम भाव", "10": "दशम भाव", "11": "एकादश भाव", "12": "द्वादश भाव",
  },
  nakshatras: {
    Ashwini: "अश्विनी",
    Bharani: "भरणी",
    Krittika: "कृत्तिका",
    Rohini: "रोहिणी",
    Mrigashira: "मृगशीर्ष",
    Ardra: "आर्द्रा",
    Punarvasu: "पुनर्वसु",
    Pushya: "पुष्य",
    Ashlesha: "आश्लेषा",
    Magha: "मघा",
    "Purva Phalguni": "पूर्व फाल्गुनी",
    "Uttara Phalguni": "उत्तर फाल्गुनी",
    Hasta: "हस्त",
    Chitra: "चित्रा",
    Swati: "स्वाती",
    Vishakha: "विशाखा",
    Anuradha: "अनुराधा",
    Jyeshtha: "ज्येष्ठा",
    Mula: "मूळ",
    "Purva Ashadha": "पूर्वाषाढा",
    "Uttara Ashadha": "उत्तराषाढा",
    Shravana: "श्रवण",
    Dhanishta: "धनिष्ठा",
    Shatabhisha: "शतभिषा",
    "Purva Bhadrapada": "पूर्व भाद्रपद",
    "Uttara Bhadrapada": "उत्तर भाद्रपद",
    Revati: "रेवती",
  },
  months: {
    January: "जानेवारी",
    February: "फेब्रुवारी",
    March: "मार्च",
    April: "एप्रिल",
    May: "मे",
    June: "जून",
    July: "जुलै",
    August: "ऑगस्ट",
    September: "सप्टेंबर",
    October: "ऑक्टोबर",
    November: "नोव्हेंबर",
    December: "डिसेंबर",
  },
  misc: {
    Mahadasha: "महादशा",
    Antardasha: "अंतर्दशा",
    "Sade Sati": "साडेसाती",
    "Not Active": "सक्रिय नाही",
    "Rising Phase": "आरंभिक टप्पा",
    "Peak Phase": "शिखर टप्पा",
    "Setting Phase": "अंतिम टप्पा",
    Ascendant: "लग्न",
    "Moon Sign": "चंद्र रास",
    "Birth Nakshatra": "जन्म नक्षत्र",
    "Planetary Positions": "ग्रह स्थिती",
    "House Analysis": "भाव विश्लेषण",
    "Career Analysis": "करिअर विश्लेषण",
    "Marriage Analysis": "विवाह विश्लेषण",
    "Health Guidance": "आरोग्य मार्गदर्शन",
    house: "भाव",
    houses: "भाव",
    sign: "रास",
    signs: "राशी",
    marriage: "विवाह",
    career: "करिअर",
    health: "आरोग्य",
    guidance: "मार्गदर्शन",
    analysis: "विश्लेषण",
    phase: "टप्पा",
    active: "सक्रिय",
    current: "सध्या",
    period: "कालावधी",
    prediction: "भविष्यवाणी",
    remedy: "उपाय",
    present: "आहे",
    absent: "नाही",
    nullified: "निवारित",
    partial: "आंशिक",
    high: "उच्च",
    medium: "मध्यम",
    low: "कमी",
    none: "नाही",
    strong: "बलवान",
    weak: "दुर्बल",
    moderate: "मध्यम",
    male: "पुरुष",
    female: "स्त्री",
    spouse: "जोडीदार",
    partner: "साथीदार",
    years: "वर्षे",
    year: "वर्ष",
    months: "महिने",
    month: "महिना",
    Siddha: "सिद्ध",
    Mangala: "मंगला",
    Pingala: "पिंगला",
    Dhanya: "धन्या",
    Bhramari: "भ्रमरी",
    Bhadrika: "भद्रिका",
    Ulka: "उल्का",
    Sankata: "संकटा",
    Debilitated: "नीच",
    Exaltation: "उच्च",
    Retrograde: "वक्री",
  },
};
