export const TA_TERM_MAPS = {
  planets: {
    Sun: "சூரியன்", Moon: "சந்திரன்", Mars: "செவ்வாய்", Mercury: "புதன்", Jupiter: "குரு", Venus: "சுக்கிரன்", Saturn: "சனி", Rahu: "ராகு", Ketu: "கேது",
  },
  signs: {
    Aries: "மேஷம்", Taurus: "ரிஷபம்", Gemini: "மிதுனம்", Cancer: "கடகம்", Leo: "சிம்மம்", Virgo: "கன்னி", Libra: "துலாம்", Scorpio: "விருச்சிகம்", Sagittarius: "தனுசு", Capricorn: "மகரம்", Aquarius: "கும்பம்", Pisces: "மீனம்",
  },
  weekdays: {
    Sunday: "ஞாயிறு", Monday: "திங்கள்", Tuesday: "செவ்வாய்", Wednesday: "புதன்", Thursday: "வியாழன்", Friday: "வெள்ளி", Saturday: "சனி",
  },
  houses: {
    "1": "முதல் பாவம்", "2": "இரண்டாம் பாவம்", "3": "மூன்றாம் பாவம்", "4": "நான்காம் பாவம்", "5": "ஐந்தாம் பாவம்", "6": "ஆறாம் பாவம்", "7": "ஏழாம் பாவம்", "8": "எட்டாம் பாவம்", "9": "ஒன்பதாம் பாவம்", "10": "பத்தாம் பாவம்", "11": "பதினோராம் பாவம்", "12": "பன்னிரண்டாம் பாவம்",
  },
  nakshatras: {
    Ashwini: "அசுவினி",
    Bharani: "பரணி",
    Krittika: "கிருத்திகை",
    Rohini: "ரோகிணி",
    Mrigashira: "மிருகசீரிடம்",
    Ardra: "திருவாதிரை",
    Punarvasu: "புனர்பூசம்",
    Pushya: "பூசம்",
    Ashlesha: "ஆயில்யம்",
    Magha: "மகம்",
    "Purva Phalguni": "பூரம்",
    "Uttara Phalguni": "உத்திரம்",
    Hasta: "அஸ்தம்",
    Chitra: "சித்திரை",
    Swati: "சுவாதி",
    Vishakha: "விசாகம்",
    Anuradha: "அனுஷம்",
    Jyeshtha: "கேட்டை",
    Mula: "மூலம்",
    "Purva Ashadha": "பூராடம்",
    "Uttara Ashadha": "உத்திராடம்",
    Shravana: "திருவோணம்",
    Dhanishta: "அவிட்டம்",
    Shatabhisha: "சதயம்",
    "Purva Bhadrapada": "பூரட்டாதி",
    "Uttara Bhadrapada": "உத்திரட்டாதி",
    Revati: "ரேவதி",
  },
  months: {
    January: "ஜனவரி",
    February: "பிப்ரவரி",
    March: "மார்ச்",
    April: "ஏப்ரல்",
    May: "மே",
    June: "ஜூன்",
    July: "ஜூலை",
    August: "ஆகஸ்ட்",
    September: "செப்டம்பர்",
    October: "அக்டோபர்",
    November: "நவம்பர்",
    December: "டிசம்பர்",
  },
  misc: {
    Mahadasha: "மகாதசை",
    Antardasha: "அந்தர்தசை",
    "Sade Sati": "சாடேசதி",
    "Not Active": "செயலில் இல்லை",
    "Rising Phase": "ஆரம்ப நிலை",
    "Peak Phase": "உச்ச நிலை",
    "Setting Phase": "இறுதி நிலை",
    Ascendant: "லக்னம்",
    "Moon Sign": "சந்திர ராசி",
    "Birth Nakshatra": "ஜன்ம நட்சத்திரம்",
    "Planetary Positions": "கிரக நிலைகள்",
    "House Analysis": "பாவ விசலேஷணை",
    "Career Analysis": "தொழில் விசலேஷணை",
    "Marriage Analysis": "திருமண விசலேஷணை",
    "Health Guidance": "ஆரோக்கிய வழிகாட்டுதல்",
    house: "பாவம்",
    houses: "பாவங்கள்",
    sign: "ராசி",
    signs: "ராசிகள்",
    marriage: "திருமணம்",
    career: "தொழில்",
    health: "ஆரோக்கியம்",
    guidance: "வழிகாட்டுதல்",
    analysis: "விசலேஷணை",
    phase: "நிலை",
    active: "செயலில்",
    current: "தற்போதைய",
    period: "காலம்",
    prediction: "பலன்",
    remedy: "பரிகாரம்",
    present: "உள்ளது",
    absent: "இல்லை",
    nullified: "நீக்கப்பட்டது",
    partial: "பகுதி",
    high: "அதிகம்",
    medium: "நடுத்தரம்",
    low: "குறைவு",
    none: "இல்லை",
    strong: "வலிமை",
    weak: "பலவீனம்",
    moderate: "நடுத்தரம்",
    male: "ஆண்",
    female: "பெண்",
    spouse: "வாழ்க்கைத்துணை",
    partner: "துணை",
    years: "ஆண்டுகள்",
    year: "ஆண்டு",
    months: "மாதங்கள்",
    month: "மாதம்",
    Siddha: "சித்த",
    Mangala: "மங்கள",
    Pingala: "பிங்கள",
    Dhanya: "தன்ய",
    Bhramari: "பிரமரி",
    Bhadrika: "பத்ரிகா",
    Ulka: "உல்கா",
    Sankata: "சங்கட",
    Debilitated: "நீசம்",
    Exaltation: "உச்சம்",
    Retrograde: "வக்கிரம்",
  },
};
